---
output:
   html_document: default
---

```{r Set up, echo=FALSE, warning=FALSE, message=FALSE}
#PLEASE DO NOT DELETE THIS FUNCTION
fmt <- rmarkdown::default_output_format(knitr::current_input())$name
knitr::opts_chunk$set(echo = TRUE)

```


```{r, results='asis', echo=FALSE}
alternateIdentifier<-uuid::UUIDgenerate(TRUE)#It is a Universally Unique Identifier (UUID) for the EML document and not for the dataset. This term is optional. A list of different identifiers can be supplied. E.g., 619a4b95-1a82-4006-be6a-7dbe3c9b33c5.
#alternateIdentifier<-LivingNorwayR::LN_alternateIdentifier(alternateIdentifier)

###########################################################
title="title" #A description of the resource that is being documented that is long enough to differentiate it from other similar resources. Multiple titles may be provided, particularly when trying to express the title in more than one language (use the "xml:lang" attribute to indicate the language if not English/en). E.g. Vernal pool amphibian density data, Isla Vista, 1990-1996.

#title<-LivingNorwayR::LN_title("title")

###########################################################
creator="creator"#The resource creator is the person or organization responsible for creating the resource itself.This eml component has a nested structure including individualName (which is required), organizationName, positionName, deliveryPoint, city, postalCode,electonicMail and order (all of which are not required)

#To generate the tags needed for individualName you need to provide a firstName and secondName to the LN_individualName() function:
firstName="firstName"
secondName="secondName"

#LN_individualName(firstName,secondName)

#creator<-LivingNorwayR::LN_creator(individualName, organizationName=NULL,positionName=NULL, deliveryPoint=NULL, city=NULL, postalCode=NULL,electonicMail=NULL, order=NULL)

###########################################################
metadataProvider="metadataProvider"#The metadataProvider is the person or organization responsible for providing documentation for the resource. See section “People and Organisations” for more details.Again this eml component is made up of several other tags. Again the only required tag is individualName (you can reuse this from above), organizationName, positionName, deliveryPointL, city, postalCode, electonicMail and userId are opttional fields. 

#LN_metadataProvider(individualName, organizationName,positionName, deliveryPoint, city, postalCode, electonicMail, userId)

###########################################################
#associatedParty="associatedParty"#An associatedParty is another person or organisation that is associated with the resource. These parties might play various roles in the creation or maintenance of the resource, and these roles should be indicated in the "role" element. See section “People and Organisations” for more details.

#associatedParty<-LivingNorwayR::add_tag(tagtype = "associatedParty", txt=associatedParty)

###########################################################
#contact="contact"#The contact field contains contact information for this dataset. This is the person or institution to contact with questions about the use, interpretation of a data set.

#contact<-LivingNorwayR::add_tag(tagtype = "contact", txt=contact)

###########################################################
pubDate="pubDate"#The date that the resource was published. The format should be represented as: CCYY, which represents a 4 digit year, or as CCYY-MM-DD, which denotes the full year, month, and day. Note that month and day are optional components. Formats must conform to ISO 8601. E.g. 2010-09-20.

#pubDate<-LN_pubDate(pubDate)


###########################################################
language="language"#The language in which the resource (not the metadata document) is written. This can be a well-known language name, or one of the ISO language codes to be more precise. GBIF recommendation is to use the ISO language code (http://vocabularies.gbif.org/vocabularies/lang). E.g., English.

#language<-LN_language(language)

###########################################################
#additionalInfo="additionalInfo"#Information regarding omissions, instructions or other annotations that resource managers may wish to include with a dataset. Basically, any information that is not characterized by the other resource metadata fields.

#additionalInfo<-LivingNorwayR::add_tag(tagtype = "additionalInfo", txt=additionalInfo)

###########################################################
#url="url"#The URL of the resource that is available online.

#url<-LivingNorwayR::add_tag(tagtype = "url", txt=url)

###########################################################
abstract="abstract"#A brief overview of the resource that is being documented.

#abstract<-LN_abstract(abstract)

```

## Project

```{r, results='asis', echo=FALSE}
project_title="project_title"#A descriptive title for the research project. E.g., Species diversity in Tennessee riparian habitats
###########################################################
personnel="personnel"#The personnel field is used to document people involved in a research project by providing contact information and their role in the project.

personnel<-LivingNorwayR::add_tag(tagtype = "personnel", txt=personnel)
###########################################################
funding="funding"#The funding field is used to provide information about funding sources for the project such as: grant and contract numbers; names and addresses of funding sources.

#funding<-LivingNorwayR::add_tag(tagtype = "funding", txt=funding)

###########################################################
studyAreaDescription="studyAreaDescription"#The studyAreaDescription field documents the physical area associated with the research project. It can include descriptions of the geographic, temporal, and taxonomic coverage of the research location and descriptions of domains (themes) of interest such as climate, geology, soils or disturbances.

#studyAreaDescription<-LivingNorwayR::add_tag(tagtype = "studyAreaDescription", txt=studyAreaDescription)

###########################################################
designDescription="designDescription"#The field designDescription contains general textual descriptions of research design. It can include detailed accounts of goals, motivations, theory, hypotheses, strategy, statistical design, and actual work. Literature citations may also be used to describe the research design.

designDescription<-LivingNorwayR::add_tag(tagtype = "designDescription", txt=designDescription)

```

## People & Organisations

```{r, results='asis', echo=FALSE}

individualName1=list(givenName="givenName", surName="surName")
individualName2=list(givenName="givenName", surName="surName")
# depending on how many indivuals there are you can add a digit to the end of the name to make it unique

#individualName1<-LivingNorwayR::add_tag(tagtype = "individual", txt=individualName1)
#individualName2<-LivingNorwayR::add_tag(tagtype = "individual", txt=individualName2)

###########################################################
organisationName="organisationName"#The full name of the organisation that is associated with the resource. This field is intended to describe which institution or overall organization is associated with the resource being described. E.g., National Center for Ecological Analysis and Synthesis

#organisationName<-LivingNorwayR::add_tag(tagtype = "organisationName", txt=organisationName)

###########################################################
positionName="positionName"#This field is intended to be used instead of a particular person or full organization name. If the associated person that holds the role changes frequently, then Position Name would be used for consistency. Note that this field, used in conjunction with 'organizationName' and 'individualName' make up a single logical originator. Because of this, an originator with only the individualName of 'Joe Smith' is NOT the same as an originator with the name of 'Joe Smith' and the organizationName of 'NSF'. Also, the positionName should not be used in conjunction with individualName unless only that individual at that position would be considered an originator for the data package. If a positionName is used in conjunction with an organizationName, then that implies that any person who currently occupies said positionName at organizationName is the originator of the data package. E.g., HAST herbarium data manager

#positionName<-LivingNorwayR::add_tag(tagtype = "positionName", txt=positionName)

###########################################################
electronicMailAddress="electronicMailAddress"#The electronic mail address is the email address for the party. It is intended to be an Internet SMTP email address, which should consist of a username followed by the @ symbol, followed by the email server domain name address. E.g. jcuadra@gbif.org

#electronicMailAddress<-LivingNorwayR::add_tag(tagtype = "electronicMailAddress", txt=electronicMailAddress)

###########################################################
deliveryPoint="deliveryPoint"#Subfield of the address field that describes the physical or electronic address of the responsible party for a resource. The delivery point field is used for the physical address for postal communication. E.g., GBIF Secretariat, Universitetsparken 15

#deliveryPoint<-LivingNorwayR::add_tag(tagtype = "deliveryPoint", txt=deliveryPoint)

###########################################################
role="role"#Use this field to describe the role the party played with respect to the resource. E.g. technician, reviewer, principal investigator, etc.

#role<-LivingNorwayR::add_tag(tagtype = "role", txt=role)

###########################################################
phone="phone"#The phone field describes information about the responsible party's telephone, be it a voice phone, fax. E.g. +4530102040


#phone<-LivingNorwayR::add_tag(tagtype = "phone", txt=phone)

###########################################################
postalCode="postalCode"#Subfield of the address field that describes the physical or electronic address of the responsible party for a resource.


#postalCode<-LivingNorwayR::add_tag(tagtype = "postalCode", txt=postalCode)

###########################################################
city="city"#Subfield of the address field that describes the physical or electronic address of the responsible party for a resource. The city field is used for the city name of the contact associated with a particular resource. E.g. San Diego.

#city<-LivingNorwayR::add_tag(tagtype = "city", txt=city)

###########################################################
country="country"#Subfield of the address field that describes the physical or electronic address of the responsible party for a resource. The country field is used for the name of the contact's country. The country name is most often derived from the ISO 3166 country code list. E.g., Japan.

#country<-LivingNorwayR::add_tag(tagtype = "country", txt=country)

###########################################################
onlineUrl="onlineUrl"#A link to associated online information, usually a web site. When the party represents an organization, this is the URL to a website or other online information about the organization. If the party is an individual, it might be their personal web site or other related online information about the party. E.g., http://www.yourdomain.edu/~doe.

#onlineUrl<-LivingNorwayR::add_tag(tagtype = "onlineUrl", txt=onlineUrl)


```

## Keyword set (General Keywords)

```{r, results='asis', echo=FALSE}
keyword="keyword"#A keyword or key phrase that concisely describes the resource or is related to the resource. Each keyword field should contain one and only one keyword (i.e., keywords should not be separated by commas or other delimiters). E.g., biodiversity.
###########################################################
keywordThesaurus="keywordThesaurus"#The name of the official keyword thesaurus from which keyword was derived. If an official thesaurus name does not exist, please keep a placeholder value such as “N/A” instead of removing this element as it is required together with the keyword element to constitute a keywordSet. E.g., IRIS keyword thesaurus.


#keyword<-LivingNorwayR::LN_keywordSet(keyword, keywordThesaurus)

```


## Coverage

### Taxonomic Coverage
```{r, results='asis', echo=FALSE}
#generalTaxonmicCoverage="generalTaxonmicCoverage"#axonomic Coverage is a container for taxonomic information about a resource. It includes a list of species names (or higher level ranks) from one or more classification systems. A description of the range of taxa addressed in the data set or collection. Use a simple comma separated list of taxa. E.g., "All vascular plants were identified to family or species, mosses and lichens were identified as moss or lichen."


###########################################################
taxonRankName="taxonRankName"#The name of the taxonomic rank for which the Taxon rank value is provided. E.g., phylum, class, genus, species.

###########################################################
taxonRankValue="taxonRankValue"#The name representing the taxonomic rank of the taxon being described. E.g. Acer would be an example of a genus rank value, and rubrum would be an example of a species rank value, together indicating the common name of red maple. It is recommended to start with Kingdom and include ranks down to the most detailed level possible.


###########################################################
commonName="commonName"	#Applicable common names; these common names may be general descriptions of a group of organisms if appropriate. E.g., invertebrates, waterfowl.

#taxonomicCoverage<-LivingNorwayR::LN_taxonomicCoverage(taxonRankName,taxonRankValue, commonName)

```


### Geographic Coverage

```{r, results='asis', echo=FALSE}
geographicDescription="geographicDescription"#A short text description of a dataset's geographic areal domain. A text description is especially important to provide a geographic setting when the extent of the dataset cannot be well described by the "boundingCoordinates". E.g., "Manistee River watershed", "extent of 7 1/2 minute quads containing any property belonging to Yellowstone National Park"

###########################################################
westBoundingCoordinate="westBoundingCoordinate"	#Subfield of boundingCoordinates field covering the W margin of a bounding box. The longitude in decimal degrees of the western-most point of the bounding box that is being described. E.g., -18.25, +25, 45.24755.



###########################################################
eastBoundingCoordinate="eastBoundingCoordinate"	#Subfield of boundingCoordinates field covering the E margin of a bounding box. The longitude in decimal degrees of the eastern-most point of the bounding box that is being described. E.g., -18.25, +25, 45.24755.



###########################################################
northBoundingCoordinate="northBoundingCoordinate"	#Subfield of boundingCoordinates field covering the N margin of a bounding box. The longitude in decimal degrees of the northern-most point of the bounding box that is being described. E.g., -18.25, +25, 65.24755.


###########################################################
southBoundingCoordinate="southBoundingCoordinate"#	Subfield of boundingCoordinates field covering the S margin of a bounding box. The longitude in decimal degrees of the southern-most point of the bounding box that is being described. E.g., -118.25, +25, 84.24755.


#LN_boundingCoordinates(westBoundingCoordinate, eastBoundingCoordinate, northBoundingCoordinate,southBoundingCoordinate)

#LN_geographicCoverage(geographicDescription, boundingCoordinates)


```


### Temporal Coverage
```{r, results='asis', echo=FALSE}
beginDate="beginDate"#	Subfield of rangeOfDates field: It may be used multiple times with a endDate field to document multiple date ranges. A single time stamp signifying the beginning of some time period. The calendar date field is used to express a date, giving the year, month, and day. The format should be one that complies with the International Standards Organization's standard 8601. The recommended format for EML is YYYY-MM-DD, where Y is the four digit year, M is the two digit month code (01 - 12, where January = 01), and D is the two digit day of the month (01 - 31). This field can also be used to enter just the year portion of a date. E.g. 2010-09-20


###########################################################
endDate="endDate"	#Subfield of rangeOfDates field: It may be used multiple times with a beginDate field to document multiple date ranges. A single time stamp signifying the end of some time period. The calendar date field is used to express a date, giving the year, month, and day. The format should be one that complies with the International Standards Organization's standard 8601. The recommended format for EML is YYYY-MM-DD, where Y is the four digit year, M is the two digit month code (01 - 12, where January = 01), and D is the two digit day of the month (01 - 31). This field can also be used to enter just the year portion of a date. E.g. 2010-09-20.


#LN_temporalCoverage(beginDate, endDate)

###########################################################
#singleDateTime="singleDateTime"#	The SingleDateTime field is intended to describe a single date and time for an event.

#singleDateTime<-LivingNorwayR::add_tag(tagtype = "singleDateTime", txt=singleDateTime)

```


## Methods

```{r, results='asis', echo=FALSE}
#methodStep="methodStep"#	The methodStep field allows for repeated sets of elements that document a series of procedures followed to produce a data object. These include text descriptions of the procedures, relevant literature, software, instrumentation, source data and any quality control measures taken.

#methodStep<-LivingNorwayR::add_tag(tagtype = "methodStep", txt=methodStep)

###########################################################
#qualityControl="qualityControl"	#The qualityControl field provides a location for the description of actions taken to either control or assess the quality of data resulting from the associated method step.

#qualityControl<-LivingNorwayR::add_tag(tagtype = "qualityControl", txt=qualityControl)

###########################################################
#sampling="sampling"#	Description of sampling procedures including the geographic, temporal and taxonomic coverage of the study.
#sampling<-LivingNorwayR::add_tag(tagtype = "sampling", txt=sampling)

###########################################################
#studyExtent="studyExtent"#	Subfield of the sampling field. The coverage field allows for a textual description of the specific sampling area, the sampling frequency (temporal boundaries, frequency of occurrence), and groups of living organisms sampled (taxonomic coverage). The field studyExtent represents both a specific sampling area and the sampling frequency (temporal boundaries, frequency of occurrence). The geographic studyExtent is usually a surrogate (representative area of) for the larger area documented in the "studyAreaDescription".

#studyExtent<-LivingNorwayR::add_tag(tagtype = "studyExtent", txt=studyExtent)

###########################################################
#samplingDescription="samplingDescription"	#Subfield of the sampling field. The samplingDescription field allows for a text-based/human readable description of the sampling procedures used in the research project. The content of this element would be similar to a description of sampling procedures found in the methods section of a journal article.

#samplingDescription<-LivingNorwayR::add_tag(tagtype = "samplingDescription", txt=samplingDescription)

```


## Intellectual Property Rights

```{r, results='asis', echo=FALSE}
#purpose="purpose"	#A description of the purpose of this dataset.

#purpose<-LivingNorwayR::add_tag(tagtype = "purpose", txt=purpose)

###########################################################

intellectualRights="intellectualRights"#	A rights management statement for the resource, or reference a service providing such information. Rights information encompasses Intellectual Property Rights (IPR), Copyright, and various Property Rights. In the case of a data set, rights might include requirements for use, requirements for attribution, or other requirements the owner would like to impose. E.g., Copyright 2001 Regents of the University of California Santa Barbara. Free for use by all individuals provided that the owners are acknowledged in any use or publication.

#intellectualRights<-LivingNorwayR::LN_intellectualRights("intellectualRights")

```

## Additional Metadata

```{r, results='asis', echo=FALSE}
#dateStamp="dateStamp"#	The dateTime the metadata document was created or modified. E.g., 2002-10-23T18:13:51.235+01:00

#dateStamp<-LivingNorwayR::add_tag(tagtype = "dateStamp", txt=dateStamp)

###########################################################
#metadataLanguage="metadataLanguage"#	The language in which the metadata document (as opposed to the resource being described by the metadata) is written. Composed of an ISO639-2/T three-letter language code and an ISO3166-1 three-letter country code. E.g., en_UK

#metadataLanguage<-LivingNorwayR::add_tag(tagtype = "metadataLanguage", txt=metadataLanguage)

###########################################################
#citation="citation"	#The citation for the work itself. See eml

#citation<-LivingNorwayR::add_tag(tagtype = "citation", txt=citation)

###########################################################
#bibliography="bibliography"#	A list of citations (see below) that form a bibliography on literature related / used in the dataset

#bibliography<-LivingNorwayR::add_tag(tagtype = "bibliography", txt=bibliography)

###########################################################
#resourceLogoUrl="resourceLogoUrl"#	URL of the logo associated with a resource. E.g., http://www.gbif.org/logo.jpg

#resourceLogoUrl<-LivingNorwayR::add_tag(tagtype = "resourceLogoUrl", txt=resourceLogoUrl)

###########################################################
#parentCollectionIdentifier="parentCollectionIdentifier"#	Subfield of collection field. Is an optional field. Identifier for the parent collection for this sub-collection. Enables a hierarchy of collections and sub collections to be built.

#parentCollectionIdentifier<-LivingNorwayR::add_tag(tagtype = "parentCollectionIdentifier", txt=parentCollectionIdentifier)

###########################################################
#collectionIdentifier="collectionIdentifier"#	Subfield of collection field. Is an optional field. The URI (LSID or URL) of the collection. In RDF, used as URI of the collection resource.

#collectionIdentifier<-LivingNorwayR::add_tag(tagtype = "collectionIdentifier", txt=collectionIdentifier)

###########################################################
#formationPeriod="formationPeriod"#	Text description of the time period during which the collection was assembled. E.g., "Victorian", or "1922 - 1932", or "c. 1750".

#formationPeriod<-LivingNorwayR::add_tag(tagtype = "formationPeriod", txt=formationPeriod)

###########################################################
#livingTimePeriod="livingTimePeriod"#	Time period during which biological material was alive (for palaeontological collections).

#livingTimePeriod<-LivingNorwayR::add_tag(tagtype = "livingTimePeriod", txt=livingTimePeriod)

###########################################################
#specimenPreservationMethod="specimenPreservationMethod"#	Picklist keyword indicating the process or technique used to prevent physical deterioration of non-living collections. Expected to contain an instance from the Specimen Preservation Method Type Term vocabulary. E.g., formaldehyde.

#specimenPreservationMethod<-LivingNorwayR::add_tag(tagtype = "specimenPreservationMethod", txt=specimenPreservationMethod)

###########################################################
#jgtiCuratorialUnit="jgtiCuratorialUnit"#	A quantitative descriptor (number of specimens, samples or batches). The actual quantification could be covered by 1) an exact number of “JGI-units” in the collection plus a measure of uncertainty (+/- x); 2) a range of numbers (x to x), with the lower value representing an exact number, when the higher value is omitted. The discussion concluded that the quantification should encompass all specimens, not only those that have not yet been digitised. This is to avoid having to update the numbers too often. The number of non-public data (not digitised or not accessible) can be calculated from the GBIF numbers as opposed to the JGTI-data.

#jgtiCuratorialUnit<-LivingNorwayR::add_tag(tagtype = "jgtiCuratorialUnit", txt=jgtiCuratorialUnit)

```

