---
title: "Test Metadata"
author: "Joseph Chipperfield"
date: "20 6 2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(uuid)
library(LivingNorwayR)
#source(file.path(Sys.getenv("WORKSPACE_LIVINGNORWAY"), "R", "LNTagFunctions.R"))
```

## Abstract

`r LNabstract("A description of the dataset")` created by `r LNcreator(tagID = "2ndCreator", individualName.firstName.tagText = "Erlend", individualName.lastName.tagText = "Nielsen")` (`r LNelectronicMail(parentID = "2ndCreator", tagText = "erlend.nielsen@nina.no")`).  There was also another creator`r LNcreator(tagID = "1stCreator")`: `r LNindividualName(parentID = "1stCreator", firstName.tagText = "Matthew", lastName.tagText = "Grainger")` who has an email address at `r LNelectronicMail(parentID = "1stCreator", tagText = "matthew.grainger@nina.no")`.  There was one more creator but his name his hidden because we are ashamed of him`r LNcreator(tagID = "hiddenCreator", individualName.firstName.tagText = "Joseph", individualName.lastName.tagText = "Chipperfield", electonicMail.tagText = "joechip90@googlemail.com", isHidden = FALSE, indivualName.firstName.isHidden = TRUE)`.
